### PR TITLE
[FEATURE] Add support for custom users table in TCA

### PR DESCRIPTION
**Pull request by xperseguers**
Resolves: #12

### CODE REVIEW

**Comment by codeFareith** [comment]
Hi @xperseguers,

I think this would be even better, if it's implemented using Signal/Slot pattern, instead of hooks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xperseguers** [comment]
Actually I'm personally against the use of signal/slot in that context, even though it's possible because it's wrong for the design pattern. A signal/slot is supposed to be an "announcement" that something is happening in the style of "fire and forget". This was the case at the beginning, and at some point, someone thought that it could replace the hooks we had if the slot could return some value, which was implemented, but broke the design pattern at the same time. We end up having hooks which are imho the good way to do this kind of extension and signal/slot which could be used but are (again) wrong.

If you prefer to use signal/slot, I would of course adapt my own "hook/slot" code to reflect that but again, I dislike the misuse of that design pattern. You can ask in Slack for other advices and opinions if you want.

**Comment by codeFareith** [comment]
Why I prefer signal/slot over hooks is because signal/slot is closer to the principles of object-oriented design - whereas hooks correspond to the paradigm of functional programming.

The code for implementing Signal/Slot is clean and easy to read - that of Hooks is simply confusing; not least because registration is done via this ugly associative array.

Even though it wasn't possible in the "original implementation" (Qt), Signal/Slot is a kind of Observer design pattern and therefore returning values back to Observer isn't a break of the design pattern in my opinion.  Consider the possibilities of Enlight's Event Manager (notify(), notifyUntil(), filter(), collect()).

But thanks to passing by reference this could be avoided in the ideal case; so the order of execution can sometimes be neglected.

In addition, with the usage of the adapter pattern, the concrete implementation can be easily decoupled.

**Comment by codeFareith** [comment]
Done via Signal/Slot in v1.2.0

**Pull request closed without merging**
